# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logviewer.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'logviewer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flogviewer.proto\x12\tlogviewer\"\xe8\x01\n\x07LogItem\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06run_id\x18\x02 \x01(\x03\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\r\n\x05level\x18\x04 \x01(\t\x12\r\n\x05phase\x18\x05 \x01(\t\x12\x11\n\ttf_req_id\x18\x06 \x01(\t\x12\x18\n\x10tf_resource_type\x18\x07 \x01(\t\x12\x18\n\x10tf_resource_name\x18\x08 \x01(\t\x12\x0f\n\x07message\x18\t \x01(\t\x12\x10\n\x08is_error\x18\n \x01(\x08\x12\x14\n\x0cis_malformed\x18\x0b \x01(\x08\x12\x10\n\x08raw_json\x18\x0c \x01(\t\"2\n\rFilterRequest\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.logviewer.LogItem\"3\n\x0e\x46ilterResponse\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.logviewer.LogItem2K\n\tLogFilter\x12>\n\x07Process\x12\x18.logviewer.FilterRequest\x1a\x19.logviewer.FilterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logviewer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGITEM']._serialized_start=31
  _globals['_LOGITEM']._serialized_end=263
  _globals['_FILTERREQUEST']._serialized_start=265
  _globals['_FILTERREQUEST']._serialized_end=315
  _globals['_FILTERRESPONSE']._serialized_start=317
  _globals['_FILTERRESPONSE']._serialized_end=368
  _globals['_LOGFILTER']._serialized_start=370
  _globals['_LOGFILTER']._serialized_end=445
# @@protoc_insertion_point(module_scope)
